name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - trimlink.website/ClientApplication/**

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Packages
        run: npm ci
        working-directory: ./trimlink.website/ClientApplication

      - name: Run Linter
        working-directory: ./trimlink.website/ClientApplication
        run: npm run lint

      - name: Prettier Check
        working-directory: ./trimlink.website/ClientApplication
        run: npm run format:check

      - name: Build Vue SPA
        working-directory: ./trimlink.website/ClientApplication
        run: npm run build

      - name: Deploy
        if: github.event_name == 'push'
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_staticweb_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations
          action: "upload"
          app_location: "/trimlink.website/ClientApplication/dist"
          skip_app_build: true
          output_location: ""
          api_location: ""